import './function.js';
import './generate-pictures.js';
import './generate-big-pictures.js';
import './form.js';
import './scale.js';
import './slider.js';
import './messege.js';
import './photo-form.js';
import './filters.js';
